title: CSC413/2516 Neural Networks and Deep Learning (Winter 2022)
description: CSC413/2516-2022 course website
sitename: uoft-CSC413
baseurl: '2022'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - contents
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
markdown: kramdown

theme: jekyll-theme-cayman
